I guess it should be import { yupResolver } from "@hookform/resolvers/yup";
Was throwing error for me:
TypeError: (0 , _hookform_resolvers__WEBPACK_IMPORTED_MODULE_8__.yupResolver) is not a function
Maybe a new update 
Do Accept the PR as this is required